### PR TITLE
Ml edits

### PR DESCRIPTION
**Pull request by mlap**
Mainly made changes to the ML paragraph block. I think we could add more on potential impacts/give more of a sense of why RL is promising. I'll take another pass at the cover letter soon; will soon push my first pass at the appendix.

### CODE REVIEW

**Comment by cboettig** [comment]
@mlap nice, thanks.  shall I merge this or want to take another pass first?

**Comment by mlap** [comment]
> @mlap nice, thanks. shall I merge this or want to take another pass first?

Hold on, going to take another pass later today.

**Comment by cboettig** [comment]
thanks, this all looks good to me.

I think there's generally a perception that (a) ML takes a lot of data, and (b) ML discards the 'classical' approach of using mechanistic models.  So I was hoping to convey that neither of these perceptions are quite accurate wrt RL, which is particularly good for dealing with ecological / changing climate issues.  Do you think that comes across or is it worth being a bit more blunt?

**Comment by mlap** [comment]
I think (b) comes across. I am trying to think of a way to make (a) more explicit but I think if I do, it might bring up other questions like whether it is a good thing to not use data to build an agent here.

**Comment by cboettig** [comment]
Thanks @mlap , excellent points.  We should probably be a bit clearer about the often-unattainable data needs of traditional ML, but we definitely want to avoid misconception that we're proposing an approach completely un-teathered from empirical evidence.  We should nod towards the fact that you can include data as part of RL training of course, but we probably also need to emphasize that the models used in the simulations are intended to be based first on estimates from data (doesn't really help the matter that our examples are not -- maybe it would help to show how that would work with some real world fisheries data).  

That confusion is maybe less of a concern with the cover letter where the editor will be familiar with the higher data requirements of most ML vs parametric models but definitely needs to be clearer in the text at least.

**Comment by cboettig** [comment]
Great, meanwhile merging this to keep things in sync

**Pull request merged**
